export { type BaseErrorType, BaseError } from "./baseError.js";

export { RPCError } from "./rpcErrors";

import coreSpaceErrors, {
  type CoreSpaceErrorsType,
} from "./coreSpace/index.js";

import eSpaceErrors, { type ESpaceErrorsType } from "./eSpace/index.js";

export {
  coreSpaceErrors,
  type CoreSpaceErrorsType,
  eSpaceErrors,
  type ESpaceErrorsType,
};

export {
  InvalidParamsError,
  EmptyEpochStringError,
  EpochNumberTooLargeError,
  InvalidDigitEpochError,
  InvalidEpochTypeError,
  MissingHexPrefixError,
  LatestMinedNotExecutedError,
  SpecifiedEpochNotExecutedError,
  InvalidHashTypeError,
  NonExistentBlockHeaderError,
  InvalidBase32AddressError,
  InvalidSize160AddressError,
  UnexpectedRpcAddressNetworkError,
  BlockHashesLimitExceededError,
  BlockNotFoundError,
  PivotChainAssumptionFailedError,
  ExceededTopicsLimitError,
  ExceededLogsLimitError,
  MissingFilterParametersError,
  RewardNotCalculatedError,
  StorageLimitOutOfRangeError,
  RlpInvalidLengthError,
  RlpIsTooShortError,
  TransactionAlreadyExistError,
  TransactionChainIdMismatchError,
  TransactionInvalidReceiverError,
  TransactionNonceTooDistantError,
  TransactionNotEnoughBaseGasError,
  TransactionTooBigError,
  TransactionZeroGasPriceError,
  UnrecoverablePubkeyError,
  GasLimitExceededError,
  NonceTooStaleError,
  OutOfBalanceError,
  TxPoolFullError,
  HigherGasPriceNeededError,
  InternalError,
  InternalNonExistentBlockHeaderError,
  CallExecutionError,
  NotExecutedDropOldNonceError,
  NotExecutedDropInvalidRecipientAddress,
  NotExecutedDropNotEnoughGasLimitError,
  NotExecutedToReconsiderPackingInvalidNonceError,
  NotExecutedToReconsiderPackingEpochHeightOutOfBoundError,
  NotExecutedToReconsiderPackingNotEnoughCashFromSponsorError,
  NotExecutedToReconsiderPackingSenderDoesNotExistError,
  NotExecutedToReconsiderPackingNotEnoughBaseFeeError,
  ExecutionErrorBumpNonceVmRevertedError,
  ExecutionErrorBumpNonceNotEnoughCashError,
  ExecutionErrorBumpNonceVmOutOfGasError,
  ExecutionErrorBumpNonceVmBadJumpDestinationError,
  ExecutionErrorBumpNonceVmBadInstructionError,
  ExecutionErrorBumpNonceVmStackUnderflowError,
  ExecutionErrorBumpNonceVmOutOfStackError,
  ExecutionErrorBumpNonceVmSubStackUnderflowError,
  ExecutionErrorBumpNonceVmOutOfSubStackError,
  ExecutionErrorBumpNonceVmInvalidSubEntryError,
  ExecutionErrorBumpNonceVmNotEnoughBalanceForStorageError,
  ExecutionErrorBumpNonceVmExceedStorageLimitError,
  ExecutionErrorBumpNonceVmBuiltInError,
  ExecutionErrorBumpNonceVmInternalContractError,
  ExecutionErrorBumpNonceVmStateDbError,
  ExecutionErrorBumpNonceVmMutableCallInStaticContextError,
  ExecutionErrorBumpNonceVmWasmError,
  ExecutionErrorBumpNonceVmOutOfBoundsError,
  ExecutionErrorBumpNonceVmRevertedByBytecodeError,
  ExecutionErrorBumpNonceVmInvalidAddressError,
  ExecutionErrorBumpNonceVmConflictAddressError,
} from "./coreSpace";
export type {
  InvalidParamsErrorType,
  EmptyEpochStringErrorType,
  EpochNumberTooLargeErrorType,
  InvalidDigitEpochErrorType,
  InvalidEpochTypeErrorType,
  MissingHexPrefixErrorType,
  InternalErrorType,
  CallExecutionErrorType,
  NotExecutedDropOldNonceErrorType,
  NotExecutedDropInvalidRecipientAddressType,
  NotExecutedDropNotEnoughGasLimitErrorType,
  NotExecutedToReconsiderPackingInvalidNonceErrorType,
  NotExecutedToReconsiderPackingEpochHeightOutOfBoundErrorType,
  NotExecutedToReconsiderPackingNotEnoughCashFromSponsorErrorType,
  NotExecutedToReconsiderPackingSenderDoesNotExistErrorType,
  NotExecutedToReconsiderPackingNotEnoughBaseFeeErrorType,
  ExecutionErrorBumpNonceVmRevertedErrorType,
  ExecutionErrorBumpNonceNotEnoughCashErrorType,
  ExecutionErrorBumpNonceVmOutOfGasErrorType,
  ExecutionErrorBumpNonceVmBadJumpDestinationErrorType,
  ExecutionErrorBumpNonceVmBadInstructionErrorType,
  ExecutionErrorBumpNonceVmStackUnderflowErrorType,
  ExecutionErrorBumpNonceVmOutOfStackErrorType,
  ExecutionErrorBumpNonceVmSubStackUnderflowErrorType,
  ExecutionErrorBumpNonceVmOutOfSubStackErrorType,
  ExecutionErrorBumpNonceVmInvalidSubEntryErrorType,
  ExecutionErrorBumpNonceVmNotEnoughBalanceForStorageErrorType,
  ExecutionErrorBumpNonceVmExceedStorageLimitErrorType,
  ExecutionErrorBumpNonceVmBuiltInErrorType,
  ExecutionErrorBumpNonceVmInternalContractErrorType,
  ExecutionErrorBumpNonceVmStateDbErrorType,
  ExecutionErrorBumpNonceVmMutableCallInStaticContextErrorType,
  ExecutionErrorBumpNonceVmWasmErrorType,
  ExecutionErrorBumpNonceVmOutOfBoundsErrorType,
  ExecutionErrorBumpNonceVmRevertedByBytecodeErrorType,
  ExecutionErrorBumpNonceVmInvalidAddressErrorType,
  ExecutionErrorBumpNonceVmConflictAddressErrorType,
} from "./coreSpace";

export {
  BlockHashesNotFoundError,
  InvalidEpochIdError,
  EthExecutionError,
  ContractExecutionRevertedError,
  IncorrectTransactionSpaceError,
  InvalidTransactionSignatureError,
  ExceedsBlockGasLimitError,
  TransactionUnderpricedError,
  InsufficientGasLimitError,
  NonceOutdatedError,
  InvalidDigitBlockError,
  InvalidBlockTypeError,
  SpecifiedBlockNotExecutedError,
  EmptyBlockStringError,
  FailedToDecodeSignedTransactionError,
  InsufficientGasError,
  InsufficientFundsError,
  ExceededMaxGasError,
  UnrecognizedTransactionTypeError,
  NonceTooHighError,
} from "./eSpace";
