import { RegisterErrorsType } from "../../types";
import { CallExecutionError } from "./callExecution";
import {
  ExecutionErrorBumpNonceNotEnoughCashError,
  ExecutionErrorBumpNonceVmBadInstructionError,
  ExecutionErrorBumpNonceVmBadJumpDestinationError,
  ExecutionErrorBumpNonceVmBuiltInError,
  ExecutionErrorBumpNonceVmConflictAddressError,
  ExecutionErrorBumpNonceVmExceedStorageLimitError,
  ExecutionErrorBumpNonceVmInternalContractError,
  ExecutionErrorBumpNonceVmInvalidAddressError,
  ExecutionErrorBumpNonceVmInvalidSubEntryError,
  ExecutionErrorBumpNonceVmMutableCallInStaticContextError,
  ExecutionErrorBumpNonceVmNotEnoughBalanceForStorageError,
  ExecutionErrorBumpNonceVmOutOfBoundsError,
  ExecutionErrorBumpNonceVmOutOfGasError,
  ExecutionErrorBumpNonceVmOutOfStackError,
  ExecutionErrorBumpNonceVmOutOfSubStackError,
  ExecutionErrorBumpNonceVmRevertedByBytecodeError,
  ExecutionErrorBumpNonceVmRevertedError,
  ExecutionErrorBumpNonceVmStackUnderflowError,
  ExecutionErrorBumpNonceVmStateDbError,
  ExecutionErrorBumpNonceVmSubStackUnderflowError,
  ExecutionErrorBumpNonceVmWasmError,
  NotExecutedDropInvalidRecipientAddress,
  NotExecutedDropNotEnoughGasLimitError,
  NotExecutedDropOldNonceError,
  NotExecutedToReconsiderPackingEpochHeightOutOfBoundError,
  NotExecutedToReconsiderPackingInvalidNonceError,
  NotExecutedToReconsiderPackingNotEnoughBaseFeeError,
  NotExecutedToReconsiderPackingNotEnoughCashFromSponsorError,
  NotExecutedToReconsiderPackingSenderDoesNotExistError,
} from "./executionOutcome";

const CallExecutionErrors: RegisterErrorsType = {
  [CallExecutionError.code]: {
    code: CallExecutionError.code,
    baseError: CallExecutionError,
    detailErrors: [
      NotExecutedDropOldNonceError,
      NotExecutedDropInvalidRecipientAddress,
      NotExecutedDropNotEnoughGasLimitError,
      NotExecutedToReconsiderPackingInvalidNonceError,
      NotExecutedToReconsiderPackingEpochHeightOutOfBoundError,
      NotExecutedToReconsiderPackingNotEnoughCashFromSponsorError,
      NotExecutedToReconsiderPackingSenderDoesNotExistError,
      NotExecutedToReconsiderPackingNotEnoughBaseFeeError,
      ExecutionErrorBumpNonceVmRevertedError,
      ExecutionErrorBumpNonceNotEnoughCashError,
      ExecutionErrorBumpNonceVmOutOfGasError,
      ExecutionErrorBumpNonceVmBadJumpDestinationError,
      ExecutionErrorBumpNonceVmBadInstructionError,
      ExecutionErrorBumpNonceVmStackUnderflowError,
      ExecutionErrorBumpNonceVmOutOfStackError,
      ExecutionErrorBumpNonceVmSubStackUnderflowError,
      ExecutionErrorBumpNonceVmOutOfSubStackError,
      ExecutionErrorBumpNonceVmInvalidSubEntryError,
      ExecutionErrorBumpNonceVmNotEnoughBalanceForStorageError,
      ExecutionErrorBumpNonceVmExceedStorageLimitError,
      ExecutionErrorBumpNonceVmBuiltInError,
      ExecutionErrorBumpNonceVmInternalContractError,
      ExecutionErrorBumpNonceVmStateDbError,
      ExecutionErrorBumpNonceVmMutableCallInStaticContextError,
      ExecutionErrorBumpNonceVmWasmError,
      ExecutionErrorBumpNonceVmOutOfBoundsError,
      ExecutionErrorBumpNonceVmRevertedByBytecodeError,
      ExecutionErrorBumpNonceVmInvalidAddressError,
      ExecutionErrorBumpNonceVmConflictAddressError,
    ],
  },
};

export default CallExecutionErrors;
